sudo: false
language: php
matrix:
  fast_finish: true
  include:
  - php: 5.5
  - php: 5.6
  - php: 7
    env:
    - EXECUTE_CS_CHECK=true
    - EXECUTE_TEST_COVERALLS=true
  - php: hhvm
  - php: nightly
  - php: hhvm-nightly
  allow_failures:
  - php: 5.5
  - php: hhvm
  - php: nightly
  - php: hhvm-nightly
before_install:
- if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then phpenv config-rm xdebug.ini ||
  return 0 ; fi
- composer self-update
- if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then composer require --dev --no-update
  satooshi/php-coveralls ; fi
install:
- travis_retry composer install --no-interaction --ignore-platform-reqs
script:
- if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/phpunit -c phpunit.travis.xml
  --coverage-clover clover.xml ; fi
- if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then ./vendor/bin/phpunit -c phpunit.travis.xml;
  fi
- if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/php-cs-fixer fix -v --diff
  --dry-run ; fi
after_script:
- if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" && $EXECUTE_TEST_COVERALLS == 'true' ]] ; then
  openssl aes-256-cbc -K $encrypted_13cee3189705_key -iv $encrypted_13cee3189705_iv
    -in deploy-key.enc -out deploy-key -d && chmod 600 deploy-key; fi
- if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/coveralls -v; fi
- if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" && $EXECUTE_TEST_COVERALLS == 'true' ]] ; then
  ./vendor/bin/phing deploy; fi
